### PR TITLE
Add a Meson build system

### PR DESCRIPTION
**Pull request by amontoison**
@nimgould @dpo @jfowkes

A few comments:
- How do we compile a single precision version of sifdecode?
- What should we do with the files `local.f`, `slct_new.f`, `slct_old.f` and `slct_older.f`?

### CODE REVIEW

**Comment by nimgould** [comment]
I am not sure there is any point in having a single-precision version (other than via sed). Remember that the SIF files themselves assume that evaluations are done in double precision. Sifdecode is a stand-alone package, and unlikely to be used other than as a first step for cutest. The current cutest converts any double remnants to single via sed if needed, and it would not be possible to include c preprocessing into these as the SIF files don't have such a thing.

The local.f slct_new.f, slct_old.f and slct_older.f files are obsolete and can be removed

**Comment by dpo** [comment]
Great, thank you. Just so things are clear, the builds called “CI” are for the old build system. Some of them fail but that’s ok. Those called “Meson” are the new ones.

**Comment by dpo** [comment]
On Cirrus, the binaries and libraries are installed to `/usr/local/bin` (on linux) and `/opt/homebrew/bin` on macOS.

https://cirrus-ci.com/task/6126501880397824

That’s not what we want. We should be able to install in a user location.

**Comment by amontoison** [comment]
> On Cirrus, the binaries and libraries are installed to `/usr/local/bin` (on linux) and `/opt/homebrew/bin` on macOS.
> 
> https://cirrus-ci.com/task/6126501880397824
> 
> That’s not what we want. We should be able to install in a user location.

We can install it in a user location with `--prefix=...`. I use a user location for builds with GHA because we can't install it otherwise?

**Comment by amontoison** [comment]
> Thank you! In `meson.yml`, you set up the Intel compilers, but I only see GFortran builds. Do you know why that is?

I forgot to add them.
I push a commit to test the Intel compilers.

**Comment by amontoison** [comment]
@jfowkes Can you add me as a collaborator for `ralna/SIFDecode` and `ralna/CUTEst`?
I need an approval everytime that I push a new commit...

**Comment by nimgould** [comment]
I added you, please check you got the invitation

**Comment by amontoison** [comment]
Thanks Nick! It works. :+1:

**Pull request merged**
