### PR TITLE
GH Action to build and test

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@nimgould @amontoison @jfowkes

Here is a continuous integration script for SIFDecode. It installs SIFDecode on Linux/macOS with gfortran/ifort using the latest ARCHDefs *release*. It's only testing simple things for now:

1. that we can call `sifdecoder --help`
2. that `sifdecoder -A {arch} ROSENBR` produces the expected files.

Feel free to suggest / submit additional useful tests. Given the interactive nature of the selection tool, I'm not testing it for now.

From here on, no one should ever commit directly to the `master` branch any more. Instead, all changes should be submitted in the form of a pull request so we can check that we have all the green lights before merging.

**Comment by amontoison** [comment]
Maybe we could add LLVM based compilers `clang / clang++ / flang`. Your CI script is quite generic now.

**Comment by dpo** [comment]
There are no C parts in SIFDecode though. We could do it in CUTEst.

**Review by amontoison — APPROVED** [review]

**Comment by dpo** [comment]
I'm going to go ahead and merge this so I can prepare a release.

**Comment by jfowkes** [comment]
@dpo agreed maybe we should enable branch protection in the settings (this disables direct pushes to master)?

**Comment by nimgould** [comment]
Also agreed, but hold off ralna/galahad for the time being, there are
too many changes at present to say that this is stable
-- 
Nicholas I. M. Gould
Scientific Computing Department            email: ***@***.***
G39, R71 Rutherford Appleton Laboratory    phone: 0(44)1235 445801
Chilton, Oxon OX11 0QX England EU
www: http://www.numerical.rl.ac.uk/people/nimg

This email and any attachments are intended solely for the use of the named recipients. If you are not the intended recipient you must not use, disclose, copy or distribute this email or any of its attachments and should notify the sender immediately and delete this email from your system. UK Research and Innovation (UKRI) has taken every reasonable precaution to minimise risk of this email or any attachments containing viruses or malware but the recipient should carry out its own virus and malware checks before opening the attachments. UKRI does not accept any liability for any losses or damages which the recipient may sustain due to presence of any viruses.

**Pull request merged**
