### PR TITLE
use /usr/bin/env bash instead of /bin/bash

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@nimgould This fails on linux because `/usr/bin/env` is too old and doesn't accept the `-S` option. I used it to pass `-f` to `bash` in `cpfile`, `rmarfile` and `rmobjfile`. Did you use `-f` so you can call those scripts with arguments containing `*` and other wildcards? I don't see them being used that way though (at least, not in this package).

**Comment by dpo** [comment]
FreeBSD builds will come in a later pull requests. I need to add a platform and compilers to ARCHDefs because it's a mixture of Linux and macOS.

**Comment by nimgould** [comment]
I suspect the -f flag is a throwback to the good old csh days where -f stops the shell starting
any startup files/resources.  Is the --noprofile the corresponding bash flag, or -i the right env one?

**Comment by dpo** [comment]
Yes it looks like `env -i` does it but I don't know how portable and mainstream that is. It appears to be working without `-i`?!

**Pull request merged**
